manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: hyhy-masa
      url-base: https://github.com/hyhy-masa
    - name: caksoylar  # <-- new entry
      url-base: https://github.com/caksoylar  
  projects:
    - name: zmk
      remote: hyhy-masa
      revision: 09ee8b42
      import: app/west.yml
    - name: pmw3610-driver-minimal
      remote: hyhy-masa
      revision: "aae0701"
      path: modules/pmw3610-driver-minimal
    - name: zmk-rgbled-widget
      remote: caksoylar
      revision: e9472d6c
  self:
    path: config
